# Welcome to Jekyll!
#
# 基本信息
title: 刚子的博客
email: qigangzhong@hotmail.com
description: .Net/Java Coder
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://qigangzhong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  qigangzhong

# 文章目录格式化
permalink: /:year/:month/:day/:title/
# 文章摘要分隔符
excerpt_separator: "\n\n\n\n"

# 评论组件
disqus_shortname: gangzi

# statistic analysis 统计代码
baidu_tongji_id: ea5433d31a8e5869587b5cd565f0c23f
google_analytics_id: UA-135642516-1

# webmaster meta
bing_meta: 8D00F36D8929A335207FBCE7F13C50B3

# 格式化文档
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 开启相关文章功能，可惜github pages不支持
# lsi: true

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# 分页
paginate: 10

# 搜索服务
algolia:
  application_id: '36883FPR2D'
  index_name:     '36883FPR2D'
  search_only_api_key: '2d40767987f704b3b04b9efce7ff49c8'

# 友情链接
# links:
#   -
#     name: 朋也
#     url: https://yiiu.co/
#   -
#     name: 朋也社区
#     url: https://dev.yiiu.co/
#   -
#     name: 开发俱乐部
#     url: https://17dev.club/
#   -
#     name: Beldon
#     url: http://blog.beldon.me/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
